
a = 1

try:
    b = a/0
except Exception as e:
    print("error")

