# try:
#     pass
# except Exception as e:
#     print("catch exception  here....")
# else:
#     print("else block will be executed only if exception is not raised....")
# finally:
#     print("will be executed irrespective of exception raised or not...")
#
#
#
# try:
#     pass
# finally:
#     print("will be executed irrespective of exception raised or not...")
#
#
#
# try:
#     pass
# except Exception as e:
#     print("catch exception  here....")
# else:
#     print("else block will be executed only if exception is not raised....")
#
#
#
#
# try:
#     pass
# except Exception as e:
#     print("catch exception  here....")
# finally:
#     print("will be executed irrespective of exception raised or not...")
#
# try:
#     pass
# except IndexError as e:
#     print("catch exception  here....")
# except Exception as e:
#     # baseException
#     print("catch exception  here....")
#
#
#
# try:
#     pass
# except Exception as e:
#     print("catch exception  here....")
# except IndexError as e:
#     # baseException
#     print("catch exception  here....")

#TODO:  exercise check try/except n finally behavior with  return/continue/brak statements...





l = [1,2]
l[3]

# a = 4
# b = 0
#
# result = a/b

print("indexerror.... ")
